// Hot water generator
// 瞬間式給湯器
package hwg

// EPC
const (
	// 動作状態
	EPC_OPERATION_STATUS = 0x80
	// 給湯器燃焼状態
	EPC_WATER_HEATER_COMBUSTION_STATUS = 0xD0
	// 給湯温度設定値
	EPC_WATER_TEMPERATURE = 0xD1
	// 給湯保温設定
	EPC_WATER_HEATER_KEEP_WARM_SETTING = 0xD2
	// 自動運転時間設定値
	EPC_AUTO_OPERATION_TIME_SETTING = 0xDA
	// 自動運転残時間
	EPC_REMAINING_AUTO_OPERATION_TIME = 0xDB
	// 風呂温度設定値
	EPC_BATH_TEMPERATURE_SETTING = 0xE1
	// 風呂給湯器燃焼状態
	EPC_BATH_WATER_HEATER_COMBUSTION_STATUS = 0xE2
	// 風呂自動モード設定
	EPC_BATH_AUTO_MODE_SETTING = 0xE3
	// 風呂追い焚き動作設定
	EPC_BATH_ADDITIONAL_HEATING_OPERATION_SETTING = 0xE4
	// 風呂足し湯動作設定
	EPC_BATH_ADDING_WATER_OPERATION_SETTING = 0xE5
	// 風呂ぬるめ動作設定
	EPC_BATH_COOLER_OPERATION_SETTING = 0xE6
	// 風呂湯量設定1 リットル単位(1byte)
	EPC_BATH_WATER_VOLUME_SETTING_1 = 0xE7
	// 風呂湯量設定2 8段階(0x31~0x38)
	EPC_BATH_WATER_VOLUME_SETTING_2 = 0xE8
	// 風呂湯量設定3 リットル単位(2byte)
	EPC_BATH_WATER_VOLUME_SETTING_3 = 0xEE
	// 風呂湯量設定4 風呂湯量を段階数で指定(0x01~0xFF)
	EPC_BATH_WATER_VOLUME_SETTING_4 = 0xD4
	// 風呂湯量設定4設定可能最大レベル(0x01~0xFF)
	EPC_MAXIMUM_LEVEL_FOR_BATH_WATER_VOLUME_SETTING_4 = 0xD5
	// 浴室優先設定
	EPC_BATH_PRIORITY_SETTING = 0xE9
	// シャワー給湯状態
	EPC_SHOWER_WATER_HEATING_STATUS = 0xEA
	// 台所給湯状態
	EPC_KITCHEN_WATER_HEATING_STATUS = 0xEB
	// 風呂動作状態監視
	EPC_BATH_OPERATION_STATUS_MONITORING = 0xEF
	// 給湯保温ON タイマ予約設定
	EPC_WATHER_HEATER_KEEP_WARM_ON_TIMER_RESERVE_SETTING = 0xEC
	// 給湯保温ON タイマ時刻設定値
	EPC_WATHER_HEATER_KEEP_WARM_ON_TIMER_TIME_SETTING = 0xED
	// 風呂自動ON タイマ予約設定
	EPC_BATH_AUTO_ON_TIMER_RESERVE_SETTING = 0x90
	// 風呂自動ON タイマ時刻設定値
	EPC_BATH_AUTO_ON_TIMER_TIME_SETTING = 0x91
	// 風呂自動ON タイマ相対時間設定値
	EPC_BATH_AUTO_ON_TIMER_RELATIVE_TIME_SETTING = 0x92
	// 音量設定値
	EPC_VOLUME_SETTING_FOR_BEEP_SOUND = 0xD6
	// ミュート設定
	EPC_MUTE_SETTING = 0xD7
)

// EDT
const (
	// ON
	EDT_ON = 0x30
	// OFF
	EDT_OFF = 0x31
	// 有
	EDT_YES = 0x41
	// 無
	EDT_NO = 0x42
)
